INITIAL_STATE = {
    "time": 6,
    "day": 1,
    "phase": "morning",
    "weather": "sunny",
    "location": "home",
    "health": 1.0,
    "energy": 1.0,
    "hunger": 0.0,
    "thirst": 0.0,
    "stress": 0.0,
    "money": 1000.0,
    "bank_balance": 1000.0,
    "efficiency": 0.8,
    "productivity": 0.8,
    "salary": 100.0,
    "experience": 0.0,
    "skill_level": 1.0,
    "job_level": "Junior",
    "promotion_progress": 0.0,
    "salary_growth": 0.0,
    "career_base_salary": 100.0,
    "market_condition": "stable",
    "food_available": 10,
    "agri_output": 0.0,
    "crop_stage": 0,
    "crop_progress": 0.0,
    "soil_quality": 0.5,
    "water_level": 1.0,
    "work_count": 0,
    "expected_agri_income": 0.0,
    "current_task": "daily_survival",
    "current_score": 0.0,
    "decision_issue": "Stable State",
    "decision_reason": "Selected due to highest expected reward based on current state",
    "decision_source": "RL Agent",
    "selected_action": "work",
    "q_values": {},
    "suggestion": {
        "primary_action": "work",
        "alternative_action": "sleep",
        "messages": [],
    },
    "decision_scores": {
        "sleep": 0.0,
        "work": 0.0,
        "farm": 0.0,
        "hospital": 0.0,
    },
    "selected_decision": "work",
    "last_action": "reset",
    "last_effect": "Environment initialized",
    "decision_history": [],
}
